language: node_js
node_js:
  - '6'
before_script:
  - npm install
script: gulp
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  repo: react-fha
  target_branch: master
  on:
    branch: master
